# Generated by Django 5.1.2 on 2024-10-31 14:22

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "model",
            "0032_rename_failureline_job_guid_repository_failure_lin_job_gui_b67c6d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="searchable_data",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
